{"uuid": "810499b9-2b46-4800-b7e8-5ff3676d74d4", "children": ["fc372f50-459e-4b1a-b72d-66d589c6adf9"], "befores": [{"name": "page_fixture", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.Error: : Tracing has been already started\n", "trace": "  File \"C:\\Users\\yurin.a\\PycharmProjects\\playwright_tests_UI\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\yurin.a\\PycharmProjects\\playwright_tests_UI\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\yurin.a\\PycharmProjects\\playwright_tests_UI\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\yurin.a\\PycharmProjects\\playwright_tests_UI\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1149, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\yurin.a\\PycharmProjects\\playwright_tests_UI\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 916, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\yurin.a\\PycharmProjects\\playwright_tests_UI\\conftest.py\", line 32, in page_fixture\n    page.context.tracing.start(screenshots=True, snapshots=True)\n  File \"C:\\Users\\yurin.a\\PycharmProjects\\playwright_tests_UI\\.venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 14769, in start\n    self._sync(\n  File \"C:\\Users\\yurin.a\\PycharmProjects\\playwright_tests_UI\\.venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ^^^^^^^^^^^^^\n  File \"C:\\Users\\yurin.a\\PycharmProjects\\playwright_tests_UI\\.venv\\Lib\\site-packages\\playwright\\_impl\\_tracing.py\", line 50, in start\n    trace_name = await self._connection.wrap_api_call(_inner_start, True)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\yurin.a\\PycharmProjects\\playwright_tests_UI\\.venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 514, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1725376578707, "stop": 1725376578734}], "start": 1725376578707, "stop": 1725376578897}